/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        primary: "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        secondary: "#ebb2ff",
        "on-secondary": "#520072",
        "secondary-container": "#b600f8",
        "on-secondary-container": "#fff6fc",
        tertiary: "#f6f5ff",
        "on-tertiary": "#2c3040",
        "tertiary-container": "#d5d8ee",
        "on-tertiary-container": "#5a5e70",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#ebb2ff",
        "on-secondary-fixed": "#320047",
        "on-secondary-fixed-variant": "#74009f",
        "tertiary-fixed": "#dee1f8",
        "tertiary-fixed-dim": "#c2c5db",
        "on-tertiary-fixed": "#171b2b",
        "on-tertiary-fixed-variant": "#424658",
        background: "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        cyan: {
          400: "#00dbe9",
          500: "#06b6d4",
          600: "#0891b2",
        },
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "unit-1": "4px",
        "unit-2": "8px",
        "unit-4": "16px",
        "unit-6": "24px",
        "unit-8": "32px",
        "unit-12": "48px",
        gutter: "20px",
        margin: "40px",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "data-display": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "data-display": ["56px", { lineHeight: "1.0", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}

